apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: sandeepnaidu
  labels:
    role: db
    env : dev
spec:
  selector:
    role: db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
    clusterIP: None
    selector:
      role: db